name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    # Should have the most commonly used packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          # Ensures latest version of .Net 10 will be used
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore BookSearchApi.slnx

      - name: Build
        run: dotnet build BookSearchApi.slnx --no-restore -c Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            BookSearchApi/bin/Release
            BookSearchApi.Tests/bin/Release

  test:
    # Should have the most commonly used packages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          # Ensures latest version of .Net 10 will be used
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore BookSearchApi.slnx

      - name: Build
        run: dotnet build BookSearchApi.slnx --no-restore -c Release

      - name: Test with code coverage
        run: dotnet test BookSearchApi.slnx --no-build -c Release --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage

      - name: Generate coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage
      
      - name: Code coverage summary
        uses: 5monkeys/cobertura-action@master
        with:
          path: ./coverage/**/coverage.cobertura.xml
          minimum_coverage: 75
          fail_below_threshold: true
          show_line: true
          show_branch: true
          show_missing: true