name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    # Should have latest standard packages that are normally used
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          # This ensures the latest version of .Net10 will be used
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore BookSearchApi.slnx

      - name: Build
        run: dotnet build BookSearchApi.slnx --no-restore -c Release

      - name: Test with code coverage
        run: dotnet test BookSearchApi.slnx --no-build -c Release --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage